info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    product_process-1_0:
      path: /product-process-1.0-SNAPSHOT/**
      serviceId: product-process_1.0-SNAPSHOT
      stripPrefix: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    com.netflix: DEBUG 